export const paths = {
  MAIN: "/",
  AUTH: "/auth/",
  PAGE_NOT_FOUND: "404",
  LOGIN: "/auth/login",
  REGISTER: "/auth/registration",
  CHECK_EMAIL: "/auth/check-email",
  SET_NEW_PASSWORD: "/auth/set-new-password/:token",
  FORGOT_PASSWORD: "/auth/forgot-password",
  PROFILE: "/profile",
  PACKS: "/packs",
  CARDS: "/cards",
  LEARN: "/learn",
  SANDBOX: "/sandbox",
} as const